Print some logs when session can't start

diff --git a/debian/tests/utils b/debian/tests/utils
--- a/debian/tests/utils
+++ b/debian/tests/utils
@@ -80,6 +80,12 @@ function wait_for_compiz {
     while [ ! `pgrep -c top` -gt 0 ]; do
         if [ $timeout -le 0 ]; then
             echo "compiz didn't start"
+            echo "------------- /var/log/lightdm/x-0.log -------------"
+            sudo -n cat  /var/log/lightdm/x-0.log || true
+            echo "------------- /var/log/lightdm/.lightdm.log -------------"
+            sudo -n cat  /var/log/lightdm/lightdm.log || true
+            echo "------------- ~/.xsession-errors -------------"
+            cat  ~/.xsession-errors || true
             exit 1
         fi
         timeout=$((timeout - 5))
